application: gm-img
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /imgboard\.css
  static_files: imgboard.css
  upload: imgboard\.css

- url: /background\.gif
  static_files: background.gif
  upload: background\.gif

- url: /.*
  script: imgboard.app

#- url: /images
#  static_dir: images

libraries:        

- name: jinja2                                                                  
  version: latest     

- name: markupsafe                                                              
  version: latest